language: csharp

services:
    - xvfb

before_install:
    #- sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libfreetype6-dev libssl-dev libudev-dev libxi-dev libxrandr-dev
    #- export orig=`pwd`
    - wget https://downloads.tuxfamily.org/godotengine/3.1/beta1/mono/Godot_v3.1-beta1_mono_x11_64.zip
    - wget https://downloads.tuxfamily.org/godotengine/3.1/beta1/mono/Godot_v3.1-beta1_mono_export_templates.tpz
    - unzip Godot_v3.1-beta1_mono_x11_64.zip
    - unzip Godot_v3.1-beta1_mono_export_templates.tpz

install:
    - mkdir -p ~/.local/share/godot/templates/3.1.beta1.mono/
    - cp -r templates/* ~/.local/share/godot/templates/3.1.beta1.mono/

script:
    - Godot_v3.1-beta1_mono_x11_64/Godot_v3.1-beta1_mono_x11.64 --export "Linux/X11" panzerdeathmatch3d-linux
